wprig/wprig

- .gitignore
- gulp/.eslintrc.json
- gulp/browserSync.js
- gulp/bundle.js
- gulp/constants.js
- gulp/images.js
- gulp/jsLibs.js
- gulp/jsMin.js
- gulp/php.js
- gulp/sassStyles.js
- gulp/scripts.js
- gulp/styles.js
- gulp/translate.js
- gulp/watch.js
- gulpfile.babel.js
- package-lock.json
- package.json
Addresses issue #35 by adding the following gulp improvements
* Use `gulp-load-plugins` to store gulp plugins in a single variable.
* Use `pump` instead of `pipe`
- See the gulp 4.0.0 docs on [why use pump](https://github.com/gulpjs/gulp/tree/master/docs/why-use-pump)
* Split functions in gulpfile.babel.js into separate files
- This allows for `gulpfile.babel.js` to simply be a task/workflow manifest and increases readability vs having one monolithic file
* ES6+ Syntax updates
* Use gulp 4 builtin sourcemaps rather than `gulp-sourcemaps`
* Run gulp from `node_modules` in `package.json` scripts
- Running the global `gulp` will use the user's local gulp installation which may be a different version than the one we expect.
* Define `rootPath` as `process.env.INIT_CWD` to avoid relative …
> gulp improvements

- dev/pluggable/lazyload/lazyload.php
> Fix is_amp_endpoint was called incorrectly

- dev/inc/template-functions.php
> Improve conditional logic in wprig_add_body_style()

- gulp/styles.js
- package-lock.json
- package.json
Addresses #44. Adds stylint making use of [`gulp-stylelint`](https://www.npmjs.com/package/gulp-stylelint) and [`stylelint-config-wordpress`](https://www.npmjs.com/package/stylelint-config-wordpress).
Add stylelint to gulp styles task.
> Add stylelint to gulp styles task

- gulp/images.js
- package.json
Addresses #61. `v1.1` copy of #63
> Use gulp-imagemin instead of gulp-image

- gulp/bundle.js
- gulp/constants.js
- gulp/translate.js
See #60. This simply ports the same changes into the new gulp structure of `v1.1`
> Use theme slug as file name and identifier when generating language and ZIP files

- gulpfile.babel.js
I noticed that gif files in the dev/images folder were not copied / processed so I added them to the `paths` object in the gulpfile
> add gif to images path

- .github/CODEOWNERS
- .gitignore
- .travis.yml
- composer.json
- composer.lock
- dev/functions.php
- dev/tests/phpunit/bootstrap-common.php
- dev/tests/phpunit/bootstrap-integration.php
- dev/tests/phpunit/bootstrap-unit.php
- dev/tests/phpunit/framework/Integration_Test_Case.php
- dev/tests/phpunit/framework/Unit_Test_Case.php
- dev/tests/phpunit/integration/Hooks_Tests.php
- dev/tests/phpunit/integration/Theme_Support_Tests.php
- dev/tests/phpunit/unit/Setup_Tests.php
- gulp/constants.js
- phpcs.xml.dist
- phpunit.integration.xml.dist
- phpunit.xml.dist
Addresses issue #22 
This PR introduces a modern PHP tests infrastructure to the the theme, for both unit and integration tests.
* Use PHPUnit for both unit and integration testing.
* For unit tests (that require to be isolated from actually running WordPress), use the `Brain\Monkey` library that is established as a unit testing tool for WordPress.
* For integration tests, use the WordPress core test suite. This kind of setup is typically used by WordPress plugins, however they typically end up mixing unit and integration tests with this approach (with true unit testing hardly being possible though).
* Three specific test classes (one for unit tests, two for integration tests) have been implemented as a start. Providing more solid test-coverage through additional tests can happen through …
> Add PHP unit and integration tests infrastructure

- README.md
Currently, the `v2.0` branch is a few commits behind `master`. That shouldn't be the case, this PR simply merges the not yet included changes from `master` into `v2.0`.
> Merge master into v2.0 branch

- gulpfile.babel.js
Very basic change to copy on a comment.
> Fix comment from singular to plural and add period at end.

- inc/assets.php
- pluggable/lazyload/lazyload.php
Based on the comments in #39.
When WP_DEBUG is `true`, the version number is the file modification time. When WP_DEBUG is `false`, the version number is the theme version.
> Force refresh assets

- assets/css/src/content.css
- assets/css/src/editor/editor-styles.css
- assets/css/src/global.css
> Fix visual regressions caused by invalid CSS values

- gulp/generateCert.js
Addresses issue # https://github.com/wprig/wprig/issues/177
Update generateCert.js to correct spelling typo on confirmation output on line 68.
> Fix spelling typo on line 68 of generateCert.js.

- assets/css/src/editor/editor-styles.css
Duplicate styles found in editor-styles.css on v2.0 
Addresses issue https://github.com/wprig/wprig/issues/178
Removed the duplicate blocks and remove one space at the start of line 5, first body tag.
> Update editor styles to remove duplicates and space.

- inc/assets.php
Iteration on PR #164.
Get the theme version dynamically instead of having to update it manually. Related to comments in #39.
> Get the theme version from theme object

- config/themeConfig.js
- gulp/php.js
- gulp/watch.js
> Issue 79 toggle phpcs

- assets/css/src/content.css
- assets/css/src/editor/editor-styles.css
Addresses issue #191 .
Update styles for the _Cover_ block (previously _Cover image_ block).
Related to WordPress/gutenberg/pull/3444.
> Update styles for Cover block

- assets/css/src/content.css
Update available block selectors mentionned as comments in content.css
> Update available block selectors

- inc/assets.php
> Use the theme version also for editor styles

- .gitignore
Addresses issue #207 by removing `.php` files from ignored files.
> Remove template files from ignored files

- assets/css/src/editor/editor-styles.css
Addresses issue #205 by removing unneeded style declarations.
> Remove unneeded styles

- CONTRIBUTING.md
- README.md
Submitting as a PR to make sure I included all the information we need/allow for discussion.
> Adding information about office hours

- assets/css/src/content.css
Addresses issue #209.
Columns styles have evolved a lot in core. Current styles were added when Columns were considered experimental. This PR removes outdated styles, removes unwanted margins and use full width column on small screens. It fixes also an issue, see screenshots.
The test page comes from the [Theme Unit Test `blocks` branch](https://raw.githubusercontent.com/WPTRT/theme-unit-test/blocks/themeunittestdata.wordpress.xml).
Before
After
> Update column styles

- inc/Base_Support/Component.php
- tests/phpunit/integration/Theme_Support_Tests.php
- tests/phpunit/unit/Base_Support/Component_Tests.php
Addresses issue #218 by adding support for responsive embedded content.
> Add support for responsive embedded content

- template-parts/footer/info.php
Addresses issue #210 by adding the privacy policy link in the footer.
> Add the privacy policy link

- assets/css/src/content.css
Addresses issue #214 by setting this element the display property to `block` instead of `inline`.
> Align .more-link with the content

- assets/css/src/content.css
Addresses issue #258 by reordering selectors.
> Fix no descending specificy for .wp-block-column

- assets/css/src/comments.css
The HSL function in line 173 was missing a comma after the second parameter.
> Add missing comma to HSL function

- CHANGELOG.md
- composer.json
- composer.lock
- template-parts/content/entry_taxonomies.php
> Upgrade WordPress coding standards to 2.0

- gulp/scripts.js
- gulp/styles.js
Addresses issue #305 by using the environment to determine wether to include or not a source map.
> Remove source map for production files

- template-parts/content/entry-attachment.php
- template-parts/content/entry.php
Addresses issue #306 by removing unneeded php end tag at the end of files.
> Remove unneeded php end tag

- assets/css/src/content.css
- assets/css/src/custom-properties.css
- assets/css/src/editor/editor-styles.css
- inc/Editor/Component.php
Addresses issue #276.
- Updates editor color array with better naming conventions. 
- Adds new colors.
- Adds CSS colors as custom properties for re-use.
- Updates font size custom properties to better naming standard.
- Updates `content.css` and `editor-styles.css` to use new custom properties.
> Add new custom colors and font names. Use CSS custom properties. 

- assets/css/src/custom-properties.css
- assets/css/src/global.css
Setting CSS variables for link colors.
> Set CSS variables for links

- inc/Styles/Component.php
> Support the optional media parameter when registering/enqueuing stylesheets

- assets/css/src/global.css
- assets/css/src/reset.css
> Move back and update CSS table of contents to global.css

- assets/css/src/content.css
- assets/css/src/custom-properties.css
- assets/css/src/editor/editor-styles.css
- assets/css/src/global.css
Addresses issue #355.
@ataylorme Not sure when stylelint has to be disabled.
> Fix custom properties without units not evaluated

- inc/Editor/Component.php
Update documentation about color palettes to explain how to disable the custom
> Document how to disable custom colors

- inc/Editor/Component.php
Addresses issue #374.
- Correct inline documentation
- Replace `standard` by `Medium` with and increase font size
- Use a capital letter for labels like the default value
> Fix regular editor font size

- assets/css/src/content.css
> Fix audio shortcode not aligned with the content

- assets/css/src/_reset.css
- assets/css/src/global.css
Addresses issue #388 and bug uncovered in PR #360.
Shields rule from Stylelint in `_reset.css`, and reorganizes rules in `global.css` to preserve cascade.
> Fix minor CSS conflicts flagged by Stylelint

- gulp/sassStyles.js
* Only implement sourcemaps in dev mode
* Change debugging output style to `expanded`
* Closes #323
> Minor sass changes

- gulp/browserSync.js
- gulp/constants.js
- gulp/editorStyles.js
- gulp/php.js
- gulp/prodFinish.js
- gulp/sassStyles.js
- gulp/scripts.js
- gulp/styles.js
- gulp/translate.js
- gulp/utils.js
- gulp/watch.js
Don't import fresh the config all over the place. Closes #265.
> Cache config

- assets/css/src/content.css
> Fix broken columns: many columns displayed as one column

- assets/css/src/content.css
Addresses issue #342 by letting margin left and margin right inherit from the `auto` value.
> Align page links with the content

- .gitignore
- README.md
- config/themeConfig.js
- readme.txt
I have BrowserSync enabled for a Rig project and the path to the certificate is local info so didn't want to commit it, which meant moving around the info constantly while I moved between branches and commits.
Enter this solution, which allows me to have a config.local.json file of untracked config info.
Thoughts?
Not necessary for 2.0. I can move around later if needed.
> IDEA: Add a local config file

- assets/css/src/content.css
Follow-up of #390 (related to #334). I missed some duplicate selectors after having resolved conflicts.
> Fix duplicate selectors

- composer.lock
Addresses issue #412. As mentioned in that issue, a bug in PHP_CodeSniffer was causing problems with dev and build tasks in PHP 7.3.x environments. This PR updates `composer.lock` with the latest version of PHP_CodeSniffer. I can confirm that running dev, build, and bundle tasks work as expected for me with this change in place.
> Update Squizlabs/PHP_CodeSniffer (fix #412)

- gulp/editorStyles.js
- gulp/styles.js
- package.json
Addresses issue #378 by adding the [`postcss-calc` plugin](https://github.com/postcss/postcss-calc).
> Reduce calc usage

- gulp/prodPrep.js
> Fail prod build if theme name is missing

- assets/css/src/_typography.css
- assets/css/src/content.css
> Update pre - simplify styles

- assets/css/src/_media.css
- assets/css/src/content.css
- assets/css/src/editor/editor-styles.css
> Move media selectors to a separate file

- README.md
Addresses issue #430 
Clarification of the folder name restrictions when installing wprig.
> Clarify naming of wprig development folder in the installation process

- gulp/constants.js
Addresses issue #484.
Adds editor styles to the production files.
> Fix missing editor styles in production files

- assets/css/src/sidebar.css
Addresses issue #457.
**Before**
**After**
> Align the sidebar below the content

- optional/custom-post-template.php
> Fix custom post template works as a page template

- assets/css/src/global.css
> Use existing variable instead of an hardcoded value

- inc/AMP/Component.php
- inc/Accessibility/Component.php
- inc/Base_Support/Component.php
- inc/Comments/Component.php
- inc/Custom_Background/Component.php
- inc/Custom_Header/Component.php
- inc/Custom_Logo/Component.php
- inc/Customizer/Component.php
- inc/Image_Sizes/Component.php
- inc/Jetpack/Component.php
- inc/Lazyload/Component.php
- inc/Localization/Component.php
- inc/Nav_Menus/Component.php
- inc/Post_Thumbnails/Component.php
- inc/Sidebars/Component.php
- inc/Theme.php
- template-parts/content/entry.php
- template-parts/content/entry_actions.php
- template-parts/content/entry_content.php
- template-parts/content/entry_thumbnail.php
- template-parts/content/error-404.php
- template-parts/content/error.php
- template-parts/content/pagination.php
- template-parts/header/navigation.php
- tests/phpunit/unit/Accessibility/Component_Tests.php
> Prefer short array syntax

- template-parts/content/entry_taxonomies.php
Addresses issue #502
Replace hardcoded values by the taxonomy name.
> Fix wrong placeholder text for custom taxonomies

- assets/css/src/_custom-media.css
- assets/css/src/_custom-properties.css
- assets/css/src/_media.css
- assets/css/src/_reset.css
- assets/css/src/content.css
- assets/css/src/global.css
Addresses issue #445.
Removes comments to disable stylelint when they were not needed.
> Fix stylelint comments

- assets/css/src/widgets.css
Removes a CSS selector that is never used.
> Remove unused selector

- inc/Comments/Component.php
- inc/Editor/Component.php
- inc/Nav_Menus/Component.php
- inc/Styles/Component.php
- inc/Template_Tags.php
- template-parts/content/entry_taxonomies.php
- tests/phpunit/unit/Base_Support/Component_Tests.php
Addresses issue #435
Follow up of #436. `back-compat.php` stays modified.
> Fix remaining arrays not using short syntax

- template-parts/footer/info.php
Addresses issue #478.
Move `the contributors` in the sentence.
> Fix i18n for site info

- CHANGELOG.md
- inc/PWA/Component.php
- inc/Theme.php
> Add support for new PWA service worker integrations

- .travis.yml
> Test PHP 7.3 on Travis

- phpcs.xml.dist
Keeps
https://github.com/wprig/wprig/blob/1d71f39eb9dcc85f1e726e44a7058eb071db068d/phpcs.xml.dist#L94-L101
> Remove duplicated rules in phpcs.xml.dist

- assets/js/src/customizer.js
- assets/js/src/lazyload.js
- assets/js/src/navigation.js
- gulp/browserSync.js
- gulp/clean.js
- gulp/constants.js
- gulp/editorStyles.js
- gulp/generateCert.js
- gulp/images.js
- gulp/php.js
- gulp/prodCompress.js
- gulp/prodPrep.js
- gulp/prodStringReplace.js
- gulp/scripts.js
- gulp/styles.js
- gulp/tests/styles.test.js
- gulp/translate.js
- gulp/utils.js
- gulp/watch.js
- package-lock.json
- package.json
> Use WordPress official ESLint config

- .travis.yml
- CHANGELOG.md
> Fix Travis-CI not executing nightly build jobs.

- CHANGELOG.md
- inc/Nav_Menus/Component.php
> Fix invalid nav menu argument

- assets/css/src/global.css
> Remove unneeded clear

- assets/css/src/content.css
- assets/css/src/global.css
Addresses issue #476.
Also replaces the value to be independent of the number of columns.
> Group selectors with same properties

- assets/css/src/_typography.css
- template-parts/content/entry_title.php
> Reduce specificity for entry-header

- assets/css/src/_blocks.css
> Fix missing space between columns

- assets/css/src/_reset.css
Updates `reset.css` to the latest version of Normalize.
> Update normalize to v8.0.1

- CHANGELOG.md
- assets/css/src/content.css
Remove the 0 padding css and add padding to the sides of full width containers
Addresses issue #708 
- [x ] Bug fix (non-breaking change which fixes an issue)
> Add padding to full width gutenberg block

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
> Update Issues Template

- tests/phpunit/framework/Unit_Test_Case.php
- tests/phpunit/unit/Accessibility/Component_Tests.php
- tests/phpunit/unit/Base_Support/Component_Tests.php
Updates test classes to line up with changes upstream.
Lets the unit tests run
> Update base test case method name set_up() -> setUp()

- assets/css/src/global.css
Minor improvements to global.css that bring it in line with WordPress coding standards, but don't change the look.
> Makes global.css compliant with WPCS

- inc/Styles/Component.php
Added 'deps' array key to Styles/Component.php to allow for wp_enqueue_style dependencies.
> added 'deps' to css files array

- inc/Comments/Component.php
Bug fix: Error message in the comment section
When deleting the AMP parts, some parts were overlooked in the previous commit, which caused an error message in the comment section. Now all AMP parts have been removed.
- [ *] Bug fix (non-breaking change which fixes an issue)
- [ - ] This pull request relates to a ticket.
- [ + ] This code is tested.
- [ - ] This change has been added to CHANGELOG.md
- [ + ] I want my code added to WP Rig.
> Bugfix Comments
