wprig/wprig

dev/footer.php

I noticed `get_sidebar()` is always called twice. Once in the page template and then, again, in the footer.php file.
I'm assuming this was just an oversight. Since its being called in some, but not all, page templates, the `get_sidebar()` should be removed from the footer so it can be called on a template basis.

Remove duplicate get_sidebar() call

---

dev/config/cssVariables.json
dev/header.php
dev/inc/template-functions.php
dev/js/navigation.js
dev/style.css

A first take at issue #1. This should address keyboard, touch, and mouse. Allows keyboard users to skip over large submenus, clicking to access what they want.
It's written in a way that still works gracefully if no JS. And I cleaned up the chevrons so they're icons now, instead of HTML entities.
Also done:
- Optimized the way we were adding the dropdown markup. We can use the "nav_menu_link_attributes" filter, which removes the need for regex.
- Added an aria-label for the <nav> and for the nav toggle.
- Added "aria-current" to the current menu item.
#1

Optimizing main menu to be accessible

---

dev/functions.php
dev/inc/customizer.php
dev/pluggable/lazyload/lazyload.php

I started using WP Rig as a parent theme and realized get_theme_file_uri() needed to be tweaked to ensure the WP Rig assets are loaded correctly.
If you dont pass the file path to get_theme_file_uri(), it gets the directory path to the current theme, which is the child theme, so the assets were throwing an error.
Passing the file path to get_theme_file_uri() ensures it checks to load the child theme first and, if the file doesn't exist, checks to load the file from the parent theme. This method allows for child themes to override assets from the parent theme.

Use get_theme_file_uri() in case of parent theme

---

dev/header.php
dev/inc/template-functions.php

After testing the main menu some more, I realized the accessibility additions for the main menu didn't work if a menu was not assigned to the "primary" menu location. They didn't work because WordPress then prints a page menu instead of a nav menu and the container markup is different.
These changes ensure the markup is the same and all of the functionality works.
The only front-end markup that changes is the outer container went from being the default `<div class="menu-main-menu-container">` to a custom class I created: `<div class="primary-menu-container">`.
I left a @TODO note to remark that the dropdown symbols do not get added for page menus if JS is disabled because the equivalent filter that we use for nav menus (walker_nav_menu_start_el) does not exist for page menus.
I also had …

Ensuring main menu works for page menus

---

composer.json

The `composer.json` file uses incorrect indentation of 4 spaces. It should be using 2 spaces, as needed for `.json` files per the `.editorconfig` rules.

Ensure composer.json follows .editorconfig indentation rules

---

.travis.yml
dev/inc/template-functions.php

When using clauses such as `if`, `if ... else` etc in `.travis.yml`, I recommend to use actual multiline statements for those. This is easily possible by prepending the current step with a pipe (`|`) character and a newline.
By using multiline statements for more complex processes, the script is easier readable. Just as we shouldn't be using inline clauses too much in PHP and JS for that reason, that should apply to the test setup scripts as well.

Use multiline statements for clauses in `.travis.yml` to improve readability/maintenance

---

dev/config/themeConfig.js
dev/footer.php
dev/style.css
gulpfile.babel.js

Addresses issue #18 
This PR separates the theme name from the theme slug and thus allows for those to work correctly for themes that do not use the same value for both (which is by far the majority).
By having a `theme.slug` with default value "wprig" and a `theme.name` with default value "WP Rig", one can easily change the two values individually. While this requires a developer to change two values instead of just one, I think it makes sense here. The replacements are then made with both values individually, per the tweaks to the gulpfile.
Closes #18.

Ensure theme slug and theme name are replaced independently

---

dev/functions.php

Addresses issue #12 
The current function `wprig_content_width()` contains code to assign the global content width.  However, that assignment is then _overwritten_ by the integer literal that comes after the `if` code block.  The end result is the global is never assigned.
This PR fixes issue #12 by:
1. Assigning the global content width when it exists. 
2. Type casting it to an integer.
3. Or assigning the default of 720 pixels when the global does not exist.
Closes #12.
I'm using a ternary structure to keep it DRY, i.e. to avoid having 2 separate variable assignments via an if/else code block design.
Alternative structure is to assign the default before the global check.  However, doing so would cause a double assignment process when the global exists.  Why is this problematic?  It …

Fixed content width to use the global when it exists.

---

.gitignore

Quite possibly the world's smallest pull request.
Corrects `bable` to `babel` in the `.gitignore` file.

Fix misspelling of babel in .gitignore file

---

README.md
composer.json

This PR does the following:
1.  Moves PHPCS dependency to `require-dev`, as it's a development tool and not for prod.
2. Adds scripts for PHPCS/WPCS.
The new scripts make it easier for developers to run PHPCS locally on the theme's code, tests (once we have them), or both.
1. `composer phpcs-dev` - runs PHPCS on the theme's `dev` folder.
2. `composer run-phpcs` - runs each of the PHPCS scripts, i.e. tests sniffer is future once we add tests.
It uses composer's `vendor/bin/phpcs` instance. 
The syntax is multi-OS friendly for Windows, Mac OS, and Linux environments.

Added composer scripts.

---

README.md
gulpfile.babel.js

Addresses issue #30. 
Adds new `watch` task monitoring `themeConfig.js` for changes and runs PHP task any time the file is updated. Compares stored theme slug with theme slug in current `themeConfig.js`, and if no match is found, skips over the `newer` filter forcing all PHP files to be reprocessed so function names are rewritten with the new slug.

Run PHP task on all files when theme slug is changed in themeConfig.js.

---

dev/functions.php

Addresses issue #33
Inverts the conditional check in `wprig_scripts()`, returning early if AMP is active, and then doing all the enqueuing.

Improve conditional logic in wprig_scripts()

---

dev/index.php

In the index.php file is a `$post_count` variable to count the posts, which is not used in the template. I don't think we need this one in the boilerplate when we don't use it.
This PR removes it.

Remove unused $post_count from index.php

---

dev/functions.php

Updating Gutenberg editor color palette theme support: colors are now passed using a single array attribute instead of multiple attributes for each color separately.
@see  https://github.com/WordPress/gutenberg/issues/6425
Addresses issue #48 
* Adding an array wrapper around existing palette colors declarations.
* Making color name translatable.
* Adding color slug.
* Changing color hex value to lower case.

Theme support for Gutenberg color palette with a single array attribute

---

gulpfile.babel.js

This PR fixes an issue with the gulp tasks for generating the language file and ZIP bundle. Those files should use the theme slug (`wprig`) as file name and identifier, not the theme name (`WP Rig`).

Use theme slug as file name and identifier when generating language and ZIP files

---

dev/css/content.css
dev/css/editor-styles.css
dev/functions.php

Addresses issue #66. 
Adds the necessary theme support and content+editor styles.

Add support for Gutenberg font sizes

---

README.md

This PR adjusts the README section on BrowserSync configuration to clarify the object and property names for the relevant section of `./dev/config/themeConfig.js`:
```javascript
browserSync: {
live: true,
proxyURL: 'wprig.test:8888',
bypassPort: '8181',
```
- `proxy` becomes `browserSync` ([see here](https://github.com/wprig/wprig/blob/v1.1/dev/config/themeConfig.js#L10))
- `URL` becomes `proxyURL` ([see here](https://github.com/wprig/wprig/blob/v1.1/dev/config/themeConfig.js#L12))

Clarify BrowserSync settings in README

---

gulp/jsLibs.js
gulp/jsMin.js
gulp/php.js
gulp/scripts.js
gulp/watch.js

Watch theme config for changes and rebuild all the things.
* Uses the [`gulp-newer` `ext` option](https://www.npmjs.com/package/gulp-newer#neweroptions) to allow files to be rebuilt when the source hasn't changed but the theme config has
* Runs all default tasks, except the BrowserSync server, when the theme config has changed
* Also alerts the user about the theme config change and rebuild
* Addresses #104

Watch theme config for changes and rebuild all the things

---

dev/css/content.css
dev/css/editor-styles.css
dev/style.css

Addresses issue #119
`rem` fallbacks to `px` have been removed.

Remove rem fallback

---

.travis.yml
dev/functions.php

In Travis-CI, project dependencies are currently installed manually and not via Composer, which is a bad practice and leads to issues such as the one noticed during #140. Composer has specific version constraints set, which need to be honored in Travis-CI as well.

Fix PHPCompatibility issues in Travis-CI

---

dev/js/navigation.js

This PR addresses issue #95 by ensuring menus aren't initialized until the DOM is loaded.
I also optimized a few lines of logic, to change to test if certain variables are "falsey" instead of strict comparing for `undefined` because "falsey" will cover `undefined` and `null`.

Don't initialize menus until DOM is loaded

---

config/themeConfig.js
gulp/constants.js
package.json
style.css

Fixes #166 
Updates my name ("Morten Rand-Hendriksen") to "The WP Rig Contributors" in all files where creators are referenced to acknowledge this project is a team effort, not my personal hobby project.

Fix #166: Update all references to me to "The WP Rig Contributors"

---

assets/css/src/global.css

Fix #135.
Fixes output error of font size caused by improperly applied `calc()` function. HT @kudesa for finding the problem and proposing the solution.

Fix incorrect value in the 'calc()' expression

---

inc/customizer.php

Addresses issue #199.
This PR allows to set the customizer script version from the theme version. When `WP_DEBUG` is enabled, it uses the filemtime.

Set customizer script version dynamically

---

README.md

Fixes #167 
Reduces body of `README.md` to make it more legible. Documentation removed has already been added to dedicated Wiki pages in the repo.

FIX #167: Simplify README.md by moving documentation to dedicated Wiki pages

---

500.php
header.php
offline.php

Addresses issue #182 
This PR adds `500.php` and `offline.php` templates to the theme, for out-of-the-box support of the PWA plugin. Having these templates provides a good foundation to developers, and they can then tweak and enhance them to their needs. Now all you need to do is activate the PWA plugin, and you're good to go in that regard.
Implementation is pretty much copying https://github.com/westonruter/twentyseventeen-westonson
Note that, along these lines, I also wrapped the navigation menu markup in a `has_nav_menu( 'primary' )` check, which was missing before. It's a good practice having such a check there in either case, here specifically though it is necessary to allow skipping the nav menu output in the `offline.php` template.
In the future, as the PWA plugin matures, we …

Add 500.php and offline.php templates.

---

config/themeConfig.js
gulp/constants.js
gulp/utils.js

Addresses issue #192 by adding a `PHPNamespace` option to `config/themeConfig.js` in order to allow PHP namespaces to be replaced.
PHP namespaces will be replaced first since they are the first key in `nameFieldDefaults` and `getStringReplacementTasks` runs `Object.keys` on `nameFieldDefaultsnameFieldDefaults` to generate the replacement order.
I remembered an [old comment from Tonya](https://github.com/wprig/wprig/pull/47#discussion_r201158200) about the `searchValue` setting of `string` with [`gulp-string-replace`](https://www.npmjs.com/package/gulp-string-replace) not replacing everything.
I dug into the code for the plugin and `string` [runs a normal `replace` instance](https://github.com/tomaszczechowski/gulp-string-replace/blob/1.1.2/index.js#L83), which replaces the first …

Update replacement function

---

inc/Editor/Component.php

Add inline comment to disable custom font sizes
> When set, users will be restricted to the default sizes provided in Gutenberg or the sizes provided via the editor-font-sizes theme support setting.

Add documentation to disable custom font sizes

---

gulp/constants.js
gulp/images.js
gulpfile.babel.js

Addresses issue #225
`screenshot.png` was being copied along with other misc files in the `prodPrep` task. Aside from copying files to the production theme, this task also runs string replacement on the files. This was causing `screenshot.png` to be corrupt. The new `screenshot` task simply copies the screenshot file without running string replacement, nor does it perform image optimization on the file.

Create a dedicated gulp task for screenshot.png

---

gulp/prodFinish.js

Addresses issue #255 
The task `prodFinish` creates the production `.zip` archive. Creation of the production `.zip` archive is configurable via `config.export.compress`, which defaults to `true`.
There is a flaw in the logic of the `prodFinish` task. All the production files are brought in with `src`, conditionally turned into a `.zip` based on `config.export.compress`, then written to the directory above the development/production themes, e.g. `wp-content/themes`. This causes all the production files to be written to `wp-content/themes` when `config.export.compress` is `false`.
This change exits the `.zip` creation process early, rather than relying of a conditional in the middle of the task, if `config.export.compress` is `false` to prevent this unwanted behaviour.

Exit the prodFinish task early if compress is false

---

assets/css/src/content.css

Addresses issue #216 
Fix duplicate selector. Change to
`ul.wp-block-latest-posts.is-grid.alignfull` and remove stylelint disable flag around code block.

Fix duplicate selector in content.css

---

config/config.default.json
gulp/styles.js

While testing v2.0, I noticed some weird CSS issues. Basically any CSS selectors with variables weren't working. Once I dug into the styles gulp process, I noticed setting "preserve" to false fixed the issue, but that there seemed to be a theme config property (convertCSSVariables) that was being used but wasn't defined in the config.
I updated the config property from "convertCSSVariables" to "preserveCSSVars" to match the process being run and updated the default config to set the preserve property to false. Now my CSS works!

Fixing bug to preserve CSS variables

---

assets/css/src/global.css
index.php
optional/archive.php
optional/category.php
optional/front-page.php
optional/search.php
template-parts/content/pagination.php

Addresses issue #274 by replacing Older posts/Newer posts by a numerical pagination.

Use numerical pagination for search results

---

assets/css/src/editor/editor-styles.css

Addresses issue #361 
Uses `@import` to import `custom-media.css` and `custom-properties.css` into `editor-styles.css` so these variables are available in the editor. The actual inclusion is handled by PostCSS Import.

Update editor styles to accept custom properties and media

---

config/config.default.json
gulp/constants.js
gulp/scripts.js
gulp/styles.js
gulp/utils.js
gulp/watch.js

Addresses issue #363 by removing the exclude for currently imported CSS files (`reset.css`, `custom-properties.css`, and `custom-media.css`) in the CSS source path. The excluded files have been moved to a configuration option and are added during the styles task, not watch tasks.
The excluded files are not processed and minified as production files, which was the original goal of having them excluded. However, I prefer them in config rather than being hard-coded.
Config options for `customProperties`, `customMedia` and `preserve` have also been added. They directly effect the options passed to postCSS without hard-coding file paths or requiring users to edit gulp files.

Don't exclude imported files in CSS source path

---

assets/css/src/content.css

Addresses issue #345 by setting a margin for entry meta. The value is `1em` (identical to paragraphs).
Result:

Fix no margin for entry meta

---

CHANGELOG.md
README.md
package.json

Addresses #336. Replaces `install` with `rig-init` in the `scripts` section of `package.json` in order to decouple `npm install` and `composer install`.
Users can now use `npm run rig-init` for both `npm install` and `composer install` without being forced to do `composer install` whenever `npm install` is run.

Add `rig-init` to npm scripts

---

assets/css/src/content.css
assets/css/src/custom-properties.css
assets/css/src/global.css

Addresses issue #346 by setting the styles from the default Quote block to `<blockquote>` and `<cite>`.
Result:

Style blockquotes like the quote block

---

assets/css/src/global.css
assets/js/src/navigation.js
template-parts/header/navigation.php

I wanted to be able to use the "small screen" and "open submenu" toggle JS functionality (present in the main menu) in other menus but it was "hard coded" to the main menu.
This breaks out that functionality into CSS selectors so multiple menus can access.
I tested on non-JS and JS but would appreciate more testing.

Separate main menu toggle functionality into CSS selectors

---

CHANGELOG.md
composer.json

Addresses issue #72. `composer run-phpcbf` can now be used to run PHPCBF installed via Composer.

Add phpcbf to Composer scripts

---

gulp/clean.js
gulp/constants.js
gulp/php.js
gulp/sassStyles.js
gulp/scripts.js
gulp/styles.js
gulp/utils.js
package-lock.json
package.json

Use [`pipeline` from `mississippi`](https://www.npmjs.com/package/mississippi#pipeline) to convert the tasks in before replacement and after replacement into a single stream. This allows a much cleaner use of `pump`.
The tasks to run before and after replacement are now in exported functions so that they can be re-used. This is a pre-requisite for writing tests for gulp tasks (#371).
Props @phated!

Single stream gulp tasks

---

gulp/editorStyles.js

Addresses issue #417. Global `preserve: false` for `postcss-import` in editor CSS

No custom properties in editor css

---

assets/js/src/navigation.js

Because the `navigation.min.js` script is loaded asynchronously in the browser, it's possible that the `DOMContentLoaded` event has already fired by the time the browser processes the script.
We can check the state of the DOM when the script loads to determine if the event should be used or if the script should initialize immediately.
Some good info here: https://javascript.info/onload-ondomcontentloaded

Initialize navigation even if DOMContentLoaded has fired

---

gulp/utils.js
gulp/watch.js

No backslashes in file paths for gulp watch
Gulp watch uses `chokidar` under the hood, which doesn't play well with backslashes in file paths. See [paulmillr/chokidar #668](https://github.com/paulmillr/chokidar/issues/668#issuecomment-357235531)
Windows uses backslashes in file paths frequently. A new utility function `backslashToForwardSlash` is introduced and used in file paths passed to gulp watch.
File paths with forward slashes are valid for Windows in a NodeJS context, so this fixes the issues of files not being watched in Windows.
Closes #492.

No backslashes in file paths sent to gulp watch

---

inc/Styles/Component.php

Addresses issue #444.
Remove the `subset` query arg to match the default value of Google Fonts (`latin`), adds inline documentation to change the default value.

Fix Google Fonts default subset

---

gulp/utils.js

Addresses issue #498
I got an error when running npm run dev:
`TypeError: path.replace is not a function`
Turns out the function sometimes receives arrays of paths, so I added support for that.
Also made the replacement into an arrow function to avoid repetition of code.
(Please go easy on me, this is my first pull request on GitHub!)

Let backslashToForwardSlash handle arrays of paths

---

assets/css/src/_typography.css

Addresses issue #462 
Quick fix of the heading color as it was not using the `color: var(--global-font-color);` but rather was specifying a HEX color value.  I assume this is a bug unless there is some reason this couldn't be used for heading colors.

Headings in _typography.css not using css variables

---

package-lock.json
package.json

The `bundle` script sets `NODE_ENV=production`. Adding `cross-env` provides Node environment variable support in Windows
Closes #494.

Add `cross-env` to `bundle` script command

---

assets/css/src/global.css
assets/js/src/navigation.js

Addresses issue #437.
Avoids the usage of a polyfill by replacing `forEach` loops by `for` loops.
Even it prevents previous errors caused by `forEach` on IE11, sub menus are not working.

Fix sub menus don't work with IE11/Edge

---

assets/css/src/global.css

Addresses issue #471.
Add missing styles. Selectors specific to page menu have not been added, because the main navigation is displayed only when there's a menu assigned to the primary location.

Highlight current menu item/ancestor in main navigation

---

assets/css/src/widgets.css
inc/Comments/Component.php
inc/Sidebars/Component.php
sidebar.php

Addresses issue #554, #555.
- Adds an `<h2>` in the sidebar
- Changes heading level for widget titles from `<h2>` to `<h3>`
- Changes heading level for the comment form title from `<h3>` to `<h2>` when there are not comments

Fix headings for widget titles and comments form

---

assets/css/src/content.css

Addresses issue #613.
Removes redundant styles with the Block Editor stylesheet.

Remove redundant styles for links when there’s a custom text color

---

gulp/constants.js
gulp/fonts.js
gulpfile.babel.js

1. Adds a folder `/assets/fonts/` 
2. Adds a relaleted gulp task, that exports the font-files containted in that folder in to the bundled theme folder. 
It is controversial whether google fonts are compliant with the GDPR. 
Therefore, I include the necessary web fonts in all my themes, which usually also brings a small performance gain. That's why I always add a folder '/assets/folder' and a matching gulp task to store webfonts inside my theme. 
Maybe it would be a good idea to integrate the code directly into WP Rig? 
If not, I could write a documentation article on how to integrate web fonts directly into the theme.  
- [+] New feature (non-breaking change which adds functionality)
- [+] This code is tested.
- [+] I want my code added to WP Rig.
I have not yet contributed code to other …

Add folder /assets/fonts and an associated gulp task

---

assets/css/src/global.css

Addresses issue #837
It's a simple fix. I've added negative z-index when the mobile menu is hidden and positive for when it shows to bring it back.
Just two lines, nothing breaking that I can see.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] This pull request relates to a ticket.
- [ x] This code is tested.
- [x ] I want my code added to WP Rig.

mobile menu fix

---

CHANGELOG.md
eslint.config.js

The reorganization of the CSS source files should be added to the changelog because it makes a big difference for users.  
By the way: I really like how tidy global.css looks now!  
There is still an empty .esignore that should be deleted. The ignore instructions are now included in the new eslint.config.js.
This is probably because I selected the wrong base branch again. Sorry. I finally figured out where I need to select it and will try to remember that in the future.

empty file deleted and added one line to the CHANGLOG.md

---

build-js.js

…scripts (fixes #899)
Addresses issue #899
When the admin script source was renamed to `.jsx`, the build no longer produced `index.min.js` and threfor the options compontent did not work anymore.
Update eslint.config.js with a minimal override to ensure build and configuration scripts are linted and may import from devDependencies. All .js files are now linted unless they are listed in the ignore section.
- [-] This change has been added to CHANGELOG.md

include .jsx files in esbuild pipeline to fixes #899 (broken options)

---

package-lock.json
package.json

Fixes #912
**Problem**
`npm run watch:css` fails with `chokidar: command not found` on a fresh install.
**Cause**
`watch:css` uses the `chokidar` binary, which is provided by `chokidar-cli`, but that package is missing.
**Solution**
Add `chokidar-cli` to `devDependencies` so the local binary is available during `npm run`.
**Test plan**
1. `npm ci`
2. `npm run watch:css`
3. CSS builds once and then watches without errors.

fix: add chokidar-cli so `watch:css` works (fixes #912)
